CXX = g++
CXXFLAGS = -Wall -Wextra -pedantic -std=c++11 -fopenmp

all: question00 question01

question00: question00.cc
	$(CXX) $(CXXFLAGS) -o $@ $^

question01: question01.cc
	$(CXX) $(CXXFLAGS) -o $@ $^

clean:
	rm -f question00 question01
